export enum SupplyTypeEnum {
  ELECTRICITY = 'ELECTRICITY',
  THERMAL_MANAGEMENT = 'THERMAL_MANAGEMENT',
  GAS_SUPPLY_ONLY = 'GAS_SUPPLY_ONLY',
  WATER = 'WATER',
  SPRAR_UTILITIES = 'SPRAR_UTILITIES',
}
