import {ExpireState} from "../enum/expire-state.enum";
import {Phase} from '../enum/phase.enum';
import {IUtilityType} from '../../utility-types/entity/utility-type.interface';
import {IConsipAgreement} from '../../consip-agreement/entity/consip-agreement.interface';
import {ISystemUser} from '../../system-users/entity/system-user.interface';
import {ISupplier} from '../../suppliers/entity/supplier.interface';
import {IAsset} from '../../assets/entity/asset.interface';
import {IBudgetChapter} from '../../budget-chapters/entity/budget-chapter.interface';
import {ICostsBorneBy} from '../../costs-borne-by/entity/costs-borne-by.interface';
import {UtilityAggregator} from '../../utility-aggregator/entity/utility-aggregator.interface';
import {IMaintenanceManager} from '../../maintenance-managers/entity/maintenance-manager.interface';

export interface IUtility {
  id: number;
  additional_notes?: string | null;
  aggregator?: UtilityAggregator | null;
  aggregator_id_fk?: number | null;
  asset?: IAsset;
  asset_id_fk: number;
  budget_chapter_code_fk: number;
  budgetChapter?: IBudgetChapter;
  consip_agreement_id?: number;
  consip_order?: string | null;
  consipAgreement?: IConsipAgreement | null;
  costs_borne_by_id_fk: number | null;
  costsBorneBy?: ICostsBorneBy | null;
  create_date: Date | null;
  created_by?: ISystemUser | null;
  created_by_user_id: number | null;
  deleted: boolean;
  disconnection_ability?: string | null;
  estimated_annual_consumption?: number | null;
  expiryStatus?: ExpireState | null;
  latitude?: string | null;
  longitude?: string | null;
  maintenance_management_id_fk: number | null;
  maintenanceManager?: IMaintenanceManager | null;
  management_expiry_date?: Date | null;
  meter_number?: string | null;
  meter_removed?: boolean | null;
  meter_verified?: boolean | null;
  notes?: string | null;
  phase_type_electric?: Phase | null;
  power_kw_electric?: number | null;
  reported_consumption_year?: number | null;
  actual_consumption?: number | null;
  security_deposit?: number | null;
  specifications?: string | null;
  supplier?: ISupplier | null;
  supplier_address?: string | null;
  supplier_id_fk?: number | null;
  supply_active?: boolean | null;
  supply_expiry_date?: Date | null;
  supply_start_date?: Date | null;
  takeover_termination_date?: Date | null;
  update_date: Date | null;
  updated_by?: ISystemUser | null;
  updated_by_user_id: number | null;
  utility_code?: string | null;
  utility_id: string;
  utility_type_id_fk: number;
  utilityType?: IUtilityType | null;
  voltage_kw_electric?: string | null;
  water_concession?: Date | null;
  wbs_gas_element?: string | null;
  order_number?: string | null;
  cig_contract?: string | null;
}
