export enum PlantType {
  THERMAL = 'THERMAL',
  ELEVATOR = 'ELEVATOR',
  FIRE_PROTECTION = 'FIRE_PROTECTION',
  PHOTOVOLTAIC = 'PHOTOVOLTAIC',
  PUBLIC_LIGHTING = 'PUBLIC_LIGHTING',
  TRAFFIC_LIGHT = 'TRAFFIC_LIGHT',
  LIFTING_PUMP = 'LIFTING_PUMP',
  FOUNTAIN = 'FOUNTAIN',
  ELECTRICAL_CABIN = 'ELECTRICAL_CABIN',
  WATER_KIOSK = 'WATER_KIOSK',
  VIDEO_SURVEILLANCE = 'VIDEO_SURVEILLANCE',
  BIKE_STATION = 'BIKE_STATION',
  POWER_POINT = 'POWER_POINT',
  WATER_POINT = 'WATER_POINT',
  SEWAGE = 'SEWAGE',
  IRRIGATION = 'IRRIGATION',
  POWERED_STREET_FURNITURE = 'POWERED_STREET_FURNITURE',
  COMPACTOR = 'COMPACTOR',
  STORMWATER = 'STORMWATER',
}

export enum PlantStatus {
  ACTIVE = 'ACTIVE',
  DECOMMISSIONED = 'DECOMMISSIONED',
  TO_VERIFY = 'TO_VERIFY',
}

export enum InspectionStatus {
  OVERDUE = 'OVERDUE',
  DUE_SOON = 'DUE_SOON',
  OK = 'OK',
  NO_DATE = 'NO_DATE',
}

export enum PositionQuality {
  PRECISE = 'PRECISE',
  FROM_ASSET = 'FROM_ASSET',
  ESTIMATED = 'ESTIMATED',
  MISSING = 'MISSING',
}

export enum FireEquipmentType {
  EXTINGUISHER = 'EXTINGUISHER',
  HYDRANT = 'HYDRANT',
  HOSE_REEL = 'HOSE_REEL',
  FIRE_BRIGADE_CONNECTION = 'FIRE_BRIGADE_CONNECTION',
}
